[rpi_nodes]
rpi1 ansible_host=192.168.137.10 device_name=rpi-1
rpi2 ansible_host=192.168.137.11 device_name=rpi-2
rpi3 ansible_host=192.168.137.12 device_name=rpi-3

[rpi_nodes:vars]
ansible_user=miai
ansible_python_interpreter=/usr/bin/python3
app_dir=/opt/rpy-rack
ollama_model=llama3